config/routes.rb
TwitterFavorites::Application.routes.draw do
  get "welcome/index"
  post "favorites/unfavorite", :as => :unfavorite
  
  match "/favorites" => "favorites#index", :as => :favorites
  
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout 

  root :to => "welcome#index"
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["user_info"]["name"]
      user.token = auth["credentials"]["token"]
      user.secret = auth["credentials"]["secret"]
    end
  end
  
    
  def self.load_config(user)
    Twitter.configure do |config|
      config.consumer_key = 'YOUR_CONSUMER_KEY'
      config.consumer_secret = 'YOUR_CONSUMER_SECRET'
      config.oauth_token = user.token
      config.oauth_token_secret = user.secret
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  respond_to :json, :xml, :html, :js

  def index
    @favorites = Twitter.favorites(current_user.uid)
    respond_with(@favorites) do |format|
      format.js
    end
  end
  
  def unfavorite
    @tweets_for_destroy = params[:tweet_ids]
    
    @tweets_for_destroy.each do |tweet|
      Twitter.favorite_destroy(tweet)
    end
    
    respond_with(@favorite) do |format|
      format.html { redirect_to favorites_url, :notice => "Tweets were removed from your favorites." }
      format.xml { redirect_to favorites_url, :notice => "Tweets were removed from your favorites." }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    #raise request.env["omniauth.auth"].to_yaml
    auth = request.env["omniauth.auth"]
    @user = User.find_by_provider_and_uid(auth["provider"],auth["uid"]) || User.create_with_omniauth(auth)
    c = User.load_config(@user)
    session[:user_id] = @user.id
    redirect_to root_url, :notice => "Signed in!"
  end
  
  def failure
    redirect_to root_path, :notice => "We were unable to log in at this time."
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Sign out!"
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(title)
    content_for :title, title || "Twitter Favorites Personal Tool"
  end
  
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/favorites/index.html.erb
<% title "Your favorites" %>

<h2>This is your favorites from Twitter!</h2>

<% form_tag unfavorite_path do %>
<table>
  <tr>
    <th></th>
    <th>tweet message<th>
  </tr>
<% @favorites.each do |favorite| %>
  <tr class="<%= cycle('even','odd') %>">
    <td><%= check_box_tag "tweet_ids[]", favorite.id_str%></td>
    <td><%= auto_link favorite.text %></td>
  </tr>
<% end %>
</table>
<hr>
<input type="checkbox" id="select_all" >Select all
<hr>
<%= submit_tag "Remove selected tweets from my favorites!" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) || "Twitter Favorites" %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="container">
  <div id="user_nav">
    <% if current_user %>
       Welcome <%= current_user.name %>!
       <%= link_to "Sign out", signout_path %>
    <% else %>
      <%= link_to "Sign in with Twitter", "/auth/twitter" %>
    <% end %>
  </div>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  <%= content_tag :h1, yield(:title)  %>
  <%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Twitter Favorites</h1>
<h2>An easy way to remove your favorited tweets.</h2>

<%= link_to 'Go to your favorites page', favorites_path %>